# Generated by Django 3.2.11 on 2022-06-05 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(related_name='dialogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('received_by_the_server', models.BooleanField(default=True, verbose_name='Получено сервером')),
                ('sent_by_the_server', models.BooleanField(default=False, verbose_name='Отправлено сервером')),
                ('received_by_the_user', models.BooleanField(default=False, verbose_name='Получено пользователем')),
                ('read_by_the_user', models.BooleanField(default=False, verbose_name='Прочитано пользователем')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.dialog', verbose_name='Сообщение диалога')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_messages', to=settings.AUTH_USER_MODEL, verbose_name='Сообщение диалога')),
            ],
            options={
                'verbose_name': 'Сообщение диалога',
                'verbose_name_plural': 'Сообщения диалогов',
            },
        ),
    ]
