# Generated by Django 3.2.11 on 2022-06-05 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogmessage',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.dialog', verbose_name='Диалог'),
        ),
        migrations.AlterField(
            model_name='dialogmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения'),
        ),
    ]
