# Generated by Django 3.2.11 on 2022-06-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20220606_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'ordering': ['-id'], 'verbose_name': 'Диалог', 'verbose_name_plural': 'Диалоги'},
        ),
        migrations.AlterModelOptions(
            name='dialogmessage',
            options={'ordering': ['-id'], 'verbose_name': 'Сообщение диалога', 'verbose_name_plural': 'Сообщения диалогов'},
        ),
    ]
