# Generated by Django 3.2.11 on 2022-02-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_transferreddisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
    ]
