# Generated by Django 3.2.11 on 2022-04-10 14:51

import diseases.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_cards', '0007_alter_resultindependentresearch_options'),
        ('pacients', '0007_pacient_treating_doctors'),
        ('diseases', '0008_alter_chronicdisease_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicdisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diseases', to='diseases.disease', verbose_name='Заболенивание'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='medicine_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diseases', to='medicine_cards.medicinecard', verbose_name='Медицинская карта'),
        ),
        migrations.AlterField(
            model_name='chronicdisease',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diseases', to='pacients.pacient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='dischargeepicris',
            name='chronic_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_epicrisis', to='diseases.chronicdisease', verbose_name='Хроничекое заболенивание'),
        ),
        migrations.AlterField(
            model_name='dischargeepicris',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_epicrisis', to='pacients.pacient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='dischargeepicrisfiles',
            name='discharge_epicris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_epicrisis_files', to='diseases.dischargeepicris'),
        ),
        migrations.AlterField(
            model_name='dischargeepicrisfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=diseases.utils.discharge_epicrisis_files_dir, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='dischargeepicrisimage',
            name='discharge_epicris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_epicrisis_images', to='diseases.dischargeepicris'),
        ),
        migrations.AlterField(
            model_name='dischargeepicrisimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=diseases.utils.discharge_epicrisis_images_dir, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='transferreddisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_diseases', to='diseases.disease', verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='transferreddisease',
            name='medicine_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_diseases', to='medicine_cards.medicinecard', verbose_name='Медицинская карта'),
        ),
        migrations.AlterField(
            model_name='transferreddisease',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_diseases', to='pacients.pacient', verbose_name='Пациент'),
        ),
    ]
