# Generated by Django 3.2.11 on 2022-04-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0009_auto_20220410_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargeepicris',
            old_name='treatment',
            new_name='epicris',
        ),
    ]
