# Generated by Django 3.2.11 on 2022-04-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diseases", "0011_auto_20220411_1602"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='chronicdisease',
        #     name='treatment',
        #     field=models.TextField(blank=True, null=True, verbose_name='Лечение'),
        # ),
        # migrations.AlterField(
        #     model_name='dischargeepicris',
        #     name='epicris',
        #     field=models.TextField(blank=True, null=True, verbose_name='Эпикриз'),
        # ),
        # migrations.AlterField(
        #     model_name='transferreddisease',
        #     name='diagnosis_date',
        #     field=models.DateField(null=True, verbose_name='Дата постановки диагноза'),
        # ),
        # migrations.AlterField(
        #     model_name='transferreddisease',
        #     name='diagnosis_year',
        #     field=models.PositiveIntegerField(null=True, verbose_name='Год постановки диагноза'),
        # ),
        # migrations.AlterField(
        #     model_name='transferreddisease',
        #     name='treatment_date',
        #     field=models.DateField(null=True, verbose_name='Дата начала лечения'),
        # ),
        # migrations.AlterField(
        #     model_name='transferreddisease',
        #     name='treatment_end_date',
        #     field=models.DateField(null=True, verbose_name='Дата окончания лечения'),
        # ),
    ]
