# Generated by Django 3.2.11 on 2022-02-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_remove_doctor_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "Врач", "verbose_name_plural": "Врачи"},
        ),
    ]
