# Generated by Django 3.2.11 on 2022-03-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20220217_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активация'),
        ),
    ]
