# Generated by Django 3.2.11 on 2022-02-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Клиника', 'verbose_name_plural': 'Клиники'},
        ),
    ]
