# Generated by Django 3.2.11 on 2022-02-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_alter_hospital_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitaltown',
            options={'verbose_name': 'Населенный пункт', 'verbose_name_plural': 'Населенные пункты'},
        ),
    ]
