export const MEDICINECARD_COMMON_GET = "MEDICINECARD_COMMON_GET";
export const MEDICINECARD_COMMON_GET_SUCCESS = "MEDICINECARD_COMMON_GET_SUCCESS";
export const PACIENT_ERROR = "PACIENT_ERROR";
export const MEDICINECARD_COMMON_PATCH_SUCCESS = "MEDICINECARD_COMMON_PATCH_SUCCESS";
export const MEDICINECARD_COMMON_PATCH_REQUEST = "MEDICINECARD_COMMON_PATCH_REQUEST";
// export const CHANGE_USER_ERORR = "CHANGE_USER_ERORR";
export const INIT_PACIENT_STATE = "INIT_PACIENT_STATE";
export const CLEAR_PACIENT_STATE = "CLEAR_PACIENT_STATE";
