export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
export const ACTIVATE_REGISTRATION_REQUEST = "ACTIVATE_REGISTRATION_REQUEST";
export const ACTIVATE_REGISTRATION_SUCCESS = "ACTIVATE_REGISTRATION_SUCCESS";
export const ACTIVATE_REGISTRATION_ERROR = "ACTIVATE_REGISTRATION_ERROR";
export const ACTIVATE_ON_LOAD = "ACTIVATE_ON_LOAD";
