# Generated by Django 3.2.11 on 2022-02-08 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20220207_2326'),
        ('pacients', '0003_alter_pacient_options'),
        ('medicine_cards', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(verbose_name='Фактическое время приема')),
                ('anamnesis', models.TextField(verbose_name='Анамнез')),
                ('complaints', models.TextField(verbose_name='Жалобы')),
                ('complaints_date', models.DateField(verbose_name='Когда впервые появились жалобы')),
                ('treatment', models.TextField(verbose_name='Лечение')),
                ('rating_for_pacient', models.FloatField(verbose_name='Оценка пациенту')),
                ('rating_for_doctor', models.FloatField(verbose_name='Оценка доктору')),
                ('appointment_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_appointment', to='appointments.appointmentorder')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_appointments', to='doctors.doctor')),
                ('doctor_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_appointments', to='doctors.doctorspecialization')),
                ('doctor_sub_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_appointments', to='doctors.doctorsubspecialization')),
                ('medicine_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_appointments', to='medicine_cards.medicinecard')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_appointments', to='pacients.pacient')),
            ],
            options={
                'verbose_name': 'Приём врача',
                'verbose_name_plural': 'Приёмы врачей',
            },
        ),
        migrations.CreateModel(
            name='AppointmentSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(verbose_name='Жалобы')),
                ('complaints_date', models.DateField(verbose_name='Когда впервые появились жалобы')),
                ('treatment', models.TextField(verbose_name='Лечение')),
                ('appointment_order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey', to='appointments.appointmentorder')),
            ],
        ),
    ]
