# Generated by Django 3.2.11 on 2022-02-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0002_alter_hospital_options"),
        ("appointments", "0002_appointmentsurvey_doctorappointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorappointment",
            name="hospital",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="doctor_appointments",
                to="hospitals.hospital",
            ),
        ),
    ]
