# Generated by Django 3.2.11 on 2022-02-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctorappointment_hospital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentsurvey',
            options={'verbose_name': 'Опросник перед приём врача', 'verbose_name_plural': 'Опросники перед приём врача'},
        ),
    ]
