# Generated by Django 3.2.11 on 2022-02-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointmentsurvey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentsurvey',
            options={'verbose_name': 'Опросник перед приёмом врача', 'verbose_name_plural': 'Опросники перед приёмом врача'},
        ),
    ]
