# Generated by Django 3.2.11 on 2022-02-17 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pacients", "0003_alter_pacient_options"),
        ("hospitals", "0003_alter_hospitaltown_options"),
        ("medicine_cards", "0003_auto_20220212_1109"),
        ("doctors", "0007_auto_20220217_2304"),
        ("appointments", "0005_alter_appointmentsurvey_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentorder",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="appointment_orders",
                to="doctors.doctor",
                verbose_name="Врач",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentorder",
            name="doctor_specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="appointment_orders",
                to="doctors.doctorspecialization",
                verbose_name="Специализация врача",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentorder",
            name="doctor_sub_specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="appointment_orders",
                to="doctors.doctorsubspecialization",
                verbose_name="Узкая специализация врача",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentorder",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="appointment_orders",
                to="hospitals.hospital",
                verbose_name="Клиника",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentorder",
            name="pacient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="appointment_orders",
                to="pacients.pacient",
                verbose_name="Пациент",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentsurvey",
            name="appointment_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="survey",
                to="appointments.appointmentorder",
                verbose_name="Заказ на приём врача",
            ),
        ),
        migrations.AlterField(
            model_name="doctorappointment",
            name="appointment_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="doctor_appointment",
                to="appointments.appointmentorder",
                verbose_name="Заказ на приём врача",
            ),
        ),
        migrations.AlterField(
            model_name="doctorappointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="doctor_appointments",
                to="doctors.doctor",
                verbose_name="Врач",
            ),
        ),
        migrations.AlterField(
            model_name="doctorappointment",
            name="doctor_specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="doctor_appointments",
                to="doctors.doctorspecialization",
                verbose_name="Специализация врача",
            ),
        ),
        migrations.AlterField(
            model_name="doctorappointment",
            name="doctor_sub_specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="doctor_appointments",
                to="doctors.doctorsubspecialization",
                verbose_name="Узкая специализация врача",
            ),
        ),
        migrations.AlterField(
            model_name="doctorappointment",
            name="hospital",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="doctor_appointments",
                to="hospitals.hospital",
                verbose_name="Клиника",
            ),
        ),
        migrations.AlterField(
            model_name="doctorappointment",
            name="medicine_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="doctor_appointments",
                to="medicine_cards.medicinecard",
                verbose_name="Медицинская карта",
            ),
        ),
        migrations.AlterField(
            model_name="doctorappointment",
            name="pacient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="doctor_appointments",
                to="pacients.pacient",
                verbose_name="Пациент",
            ),
        ),
    ]
