# Generated by Django 3.2.11 on 2022-05-22 11:29

import appointments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_alter_hospitaltown_options'),
        ('appointments', '0007_auto_20220418_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentorder',
            name='hospital',
            field=models.ForeignKey(default=appointments.models.default_hospital, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_orders', to='hospitals.hospital', verbose_name='Клиника'),
        ),
    ]
