# Generated by Django 3.2.11 on 2022-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointmentorder_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentorder',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание приема'),
        ),
    ]
