# Generated by Django 3.2.11 on 2022-06-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedules', '0007_alter_workday_breaks'),
        ('appointments', '0009_appointmentorder_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentorder',
            name='workday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_orders', to='work_schedules.workday', verbose_name='Рабочий период'),
        ),
    ]
