# Generated by Django 3.2.11 on 2022-07-06 11:12

from django.db import migrations, models
import django.db.models.deletion
import hospitals.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_alter_hospitaltown_options'),
        ('appointments', '0011_alter_appointmentorder_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentorder',
            name='hospital',
            field=models.ForeignKey(default=hospitals.models.get_default_hospital_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_orders', to='hospitals.hospital', verbose_name='Клиника'),
        ),
    ]
