version: '3'

volumes:
  propacienta_local_postgres_data: {}
  propacienta_local_postgres_data_backups: {}
  pgadmin-data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: propacienta_local_django
    container_name: propacienta_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: propacienta_production_postgres
    container_name: propacienta_local_postgres
    volumes:
      - propacienta_local_postgres_data:/var/lib/postgresql/data:Z
      - propacienta_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  #docs:
  #  image: propacienta_local_docs
  #  container_name: propacienta_local_docs
  #  build:
  #    context: .
  #    dockerfile: ./compose/local/docs/Dockerfile
  #  env_file:
  #    - ./.envs/.local/.django
  #  volumes:
  #    - ./docs:/docs:z
  #    - ./config:/app/config:z
  #    - ./propacienta:/app/propacienta:z
  #  ports:
  #    - "7000:7000"
  #  command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: propacienta_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: propacienta_local_redis

  celeryworker:
    <<: *django
    image: propacienta_local_celeryworker
    container_name: propacienta_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: propacienta_local_celerybeat
    container_name: propacienta_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: propacienta_local_flower
    container_name: propacienta_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  reverse_proxy:
    image: nginx:latest
    volumes:
      - ./compose/local/nginx.conf:/etc/nginx/nginx.conf
      - ./propacienta/media:/web/media:z
    network_mode: host

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin