version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_nginx_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: propacienta_production_django
    volumes:
      - production_nginx_media:/app/propacienta/media:z
    
    depends_on:
      # - pgbouncer
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: propacienta_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
  
  # pgbouncer:
  #   image: edoburu/pgbouncer
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ./.envs/.production/.pgbouncer
  
  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: propacienta_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: propacienta_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: propacienta_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: propacienta_production_flower
    command: /start-flower

  # nginx-media:
  #   image: "nginx:latest"
  #   depends_on:
  #     - django
  #   volumes:
  #     - production_nginx_media:/usr/share/nginx/html/media:ro

  coturn: # add certificates ssl
    image: instrumentisto/coturn:4.5.2
    network_mode: host
    ports:
      - "3478:3478"
      - "49152-65535:49152-65535"
    volumes:
      - ./compose/production/coturn/coturn.conf:/etc/coturn/turnserver.conf
    restart: unless-stopped


  reverse_proxy:
    # image: nginx:latest
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    depends_on:
      - django
    volumes:
      - production_nginx_media:/web/media:ro

  traefik-certs-dumper:
    image: alpine
    entrypoint: ["sh", "-c", "/certs/entrypoint.sh"]
    depends_on:
      - traefik
    volumes:
      - ./compose/production/traefik/certs:/certs
      - production_traefik:/data


  redis_mailu:
    image: redis:6
    restart: unless-stopped
    volumes:
      - "./mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front_mailu:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    logging:
      driver: json-file
    ports:
      # - "185.182.111.231:80:80"
      # - "185.182.111.231:443:443"
      - "0.0.0.0:25:25"
      - "0.0.0.0:465:465"
      - "0.0.0.0:587:587"
      - "0.0.0.0:110:110"
      - "0.0.0.0:995:995"
      - "0.0.0.0:143:143"
      - "0.0.0.0:993:993"
    volumes:
      - "./compose/production/traefik/certs:/certs:ro"
      # - "/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
      - traefik
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: ./mailu/mailu.env
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    volumes:
      - "./mailu/data:/data"
      - "./mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    volumes:
      - "./mailu/mail:/mail"
      - "./mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front_mailu
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    volumes:
      - "./mailu/mailqueue:/queue"
      - "./mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front_mailu
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
    hostname: antispam
    restart: unless-stopped
    env_file: mailu.env
    volumes:
      - "./mailu/filter:/var/lib/rspamd"
      - "./mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front_mailu
      - resolver
    dns:
      - 192.168.203.254
