# Generated by Django 3.2.11 on 2022-03-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_cards', '0005_rename_datetime_resultindependentresearch_datetime_stamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultindependentresearch',
            options={'ordering': ['-id'], 'verbose_name': 'Результат самостоятельного исследования', 'verbose_name_plural': 'Результаты самостоятельных исследований'},
        ),
    ]
