# Generated by Django 3.2.11 on 2022-10-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_cards', '0008_auto_20220412_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinecard',
            name='blood_type',
            field=models.CharField(choices=[('I−', 'O(I) Rh−'), ('I+', 'O(I) Rh+'), ('II−', 'A(II) Rh−'), ('II+', 'A(II) Rh+'), ('III−', 'B(III) Rh−'), ('III+', 'B(III) Rh+'), ('IV−', 'AB(IV) Rh−'), ('IV+', 'AB(IV) Rh+')], default='I−', max_length=6, verbose_name='Группа крови'),
        ),
        migrations.AddField(
            model_name='medicinecard',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=6, verbose_name='Пол'),
        ),
    ]
