# Generated by Django 3.2.11 on 2022-02-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operation",
            options={"verbose_name": "Операция", "verbose_name_plural": "Операции"},
        ),
    ]
