# Generated by Django 3.2.11 on 2022-05-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20220503_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-id'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='transferredoperation',
            options={'ordering': ['-id'], 'verbose_name': 'Перенесенная операция', 'verbose_name_plural': 'Перенесенные операции'},
        ),
    ]
