# Generated by Django 3.2.11 on 2022-09-20 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='Идентификатор')),
                ('start_webdial', models.DateTimeField(auto_now_add=True, verbose_name='Начало разговора')),
                ('end_webdial', models.DateTimeField(blank=True, verbose_name='Окончание разговора')),
                ('webdial_duration', models.DurationField(blank=True, verbose_name='Продолжительность разговора')),
                ('end_webdial_reason', models.CharField(blank=True, choices=[('initiator', 'Инициатор'), ('opponent', 'Вызываемый'), ('error', 'Ошибка'), ('opponent_reject', 'Отбой')], default='error', max_length=20, verbose_name='Причина окончания разговора')),
                ('webdial_happen', models.BooleanField(default=False, verbose_name='Звонок состоялся')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initiator_webdials', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='opponent_webdials', to=settings.AUTH_USER_MODEL, verbose_name='Вызываемый пользователь')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['-id'],
            },
        ),
    ]
