# Generated by Django 3.2.11 on 2022-02-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20220207_2326'),
        ('analisis', '0004_analysis_diseases'),
        ('procedures', '0001_initial'),
        ('medicine_cards', '0003_auto_20220212_1109'),
        ('appointments', '0005_alter_appointmentsurvey_options'),
        ('medicines', '0001_initial'),
        ('prescriptions', '0002_auto_20220213_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisprescription',
            name='analisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analisis_prescriptions', to='analisis.analysis', verbose_name='Анализ'),
        ),
        migrations.AlterField(
            model_name='analisisprescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analisisprescription', to='doctors.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='analisisprescription',
            name='doctor_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analisisprescription', to='appointments.doctorappointment', verbose_name='Прием врача'),
        ),
        migrations.AlterField(
            model_name='analisisprescription',
            name='medicine_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analisisprescription', to='medicine_cards.medicinecard', verbose_name='Медицинская карта'),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicineprescription', to='doctors.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='doctor_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicineprescription', to='appointments.doctorappointment', verbose_name='Прием врача'),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicine_prescriptions', to='medicines.medicine', verbose_name='Медикамент'),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='medicine_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicineprescription', to='medicine_cards.medicinecard', verbose_name='Медицинская карта'),
        ),
        migrations.AlterField(
            model_name='procedureprescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedureprescription', to='doctors.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='procedureprescription',
            name='doctor_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedureprescription', to='appointments.doctorappointment', verbose_name='Прием врача'),
        ),
        migrations.AlterField(
            model_name='procedureprescription',
            name='medicine_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedureprescription', to='medicine_cards.medicinecard', verbose_name='Медицинская карта'),
        ),
        migrations.AlterField(
            model_name='procedureprescription',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure_prescriptions', to='procedures.procedure', verbose_name='Процедура'),
        ),
    ]
