# Generated by Django 3.2.11 on 2022-02-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Patronymic"
            ),
        ),
    ]
