# Generated by Django 3.2.11 on 2022-07-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_auto_20220430_1547'),
        ('users', '0007_auto_20220226_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='doctors.doctor'),
        ),
    ]
