# Generated by Django 3.2.11 on 2022-02-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diseases", "0002_transferreddisease"),
        ("analisis", "0003_auto_20220212_1059"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="diseases",
            field=models.ManyToManyField(
                related_name="analyzis",
                to="diseases.Disease",
                verbose_name="Заболевания",
            ),
        ),
    ]
