# Generated by Django 3.2.11 on 2022-03-21 21:16

import analisis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analisis", "0006_alter_analysis_diseases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisresultsfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=analisis.utils.analisis_results_files_dir,
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="analysisresultsimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=analisis.utils.analisis_results_images_dir,
                verbose_name="Фото",
            ),
        ),
    ]
