# Generated by Django 3.2.11 on 2022-05-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0015_auto_20220430_1547'),
        ('hospitals', '0003_alter_hospitaltown_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False, verbose_name='Дата')),
                ('since', models.TimeField(verbose_name='Начало периода работы')),
                ('to', models.TimeField(verbose_name='Окончание периода работы')),
                ('appointment_duration', models.IntegerField(choices=[(15, '15 минут'), (30, '30 минут'), (45, '45 минут'), (60, '60 минут')], default=15, editable=False, verbose_name='Продолжительность приема в минутах')),
                ('timeslotmask', models.CharField(blank=True, help_text='Последовательность 0 и 1 для фильтрации уже занятых временных слотов,\n        где 0 - свободный 15-ти минутный интервал, 1 - занятый. Максимальная длина\n        соответсвует максимальному количеству 15-ти минутных интервалов в сутках.', max_length=96, verbose_name='Маска занятости рабочего времени')),
                ('doctor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='doctors.doctor', verbose_name='Врач')),
                ('hospital', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='hospitals.hospital', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NotWorkingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('weekend', 'Выходной'), ('vacation', 'Отпуск'), ('disease', 'Болезнь'), ('pregnancy', 'Беременность'), ('business_trip', 'Коммандировка')], default='weekend', max_length=20, verbose_name='Причина')),
                ('since', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('to', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_open', models.BooleanField(default=True, help_text='Для фильтрации', verbose_name='Статус неоконченности периода')),
                ('doctor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='not_working_periods', to='doctors.doctor', verbose_name='Врач')),
                ('hospital', models.ManyToManyField(related_name='not_working_periods', to='hospitals.Hospital', verbose_name='Клиники')),
            ],
        ),
    ]
