# Generated by Django 3.2.11 on 2022-05-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_alter_hospitaltown_options'),
        ('doctors', '0015_auto_20220430_1547'),
        ('work_schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notworkingperiod',
            options={'ordering': ['-id'], 'verbose_name': 'Нерабочий период', 'verbose_name_plural': 'Нерабочие периоды'},
        ),
        migrations.AlterField(
            model_name='workday',
            name='appointment_duration',
            field=models.IntegerField(choices=[(15, '15 минут'), (30, '30 минут'), (45, '45 минут'), (60, '60 минут')], default=15, verbose_name='Продолжительность приема в минутах'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='doctors.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='hospitals.hospital', verbose_name='Клиника'),
        ),
    ]
