# Generated by Django 3.2.11 on 2022-05-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedules', '0003_alter_notworkingperiod_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='have_a_rest_timeslotmask',
            field=models.CharField(blank=True, default='', max_length=1440, verbose_name='Маска перерывов рабочего времени'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='timeslotmask',
            field=models.CharField(blank=True, help_text='Последовательность 0 и 1 для фильтрации уже занятых временных слотов,\n        где 0 - свободный 15-ти минутный интервал, 1 - занятый. Максимальная длина\n        соответсвует максимальному количеству 15-ти минутных интервалов в сутках.', max_length=1440, verbose_name='Маска занятости рабочего времени'),
        ),
    ]
