# Generated by Django 3.2.11 on 2022-06-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_schedules', '0006_alter_workday_breaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='breaks',
            field=models.JSONField(default=dict, help_text='Перерывы рабочего времени,\n        например {"breaks": [{"end": "1215", "start": "1200"}, {"end": "1545", "start": "1515"}]}', verbose_name='Перерывы'),
        ),
    ]
